pr: none
trigger: none

variables:
- group: mlops-wsh-vg

stages:
- stage: 'Dev'
  displayName: 'Dev'
  jobs:
  - job: "Provision_Dev"
    displayName: "Provision Dev resources"
    pool: myagent
    timeoutInMinutes: 0
    steps:
    - task: GitHubRelease@1
      inputs:
        gitHubConnection: 'chongyaowang'
        repositoryName: 'chongyaowang/MLOps_Workshop'
        action: 'edit'
        target: '$(Build.SourceVersion)'
        tag: '$(myTagName)'
        changeLogCompareToRelease: 'lastFullRelease'
        changeLogType: 'commitBased'
    